### ISSUE TITLE
Semantic UI conflicts with Gutenberg styles

### ISSUE THREAD

**Issue by Grawl** [mehranabi/laravel-laraberg#2]
CSS of [Semantic UI](https://semantic-ui.com) conflicts with Gutenberg CSS, causing following:

![image](https://user-images.githubusercontent.com/846774/57021771-88df8e00-6c70-11e9-950f-a79e3d3ada4a.png)

![image](https://user-images.githubusercontent.com/846774/57021794-985ed700-6c70-11e9-9dad-04d5a544757b.png)

If I remove Semantic UI CSS from layout, Gutenberg looks and works without problems.

**Comment by Grawl** [comment]
I rewrote frontend from Fomantic UI to [UIKit](https://getuikit.com), check it out: https://github.com/Grawl/laravel-laraberg/commit/b4f162d4b41038a8ae84026f3fde6fad191438b6

**Comment by Grawl** [comment]
Just checked out how Gutenberg works with Bootstrap and it's without problems too, but I like UIKit more and don't like Bootstrap. But a lot of admin panels for Laravel is built with Bootstrap, even with old 3rd version.

**Comment by mehranabi** [comment]
Oh, Thank you @Grawl for checking out, I missed that issue with semantic-ui!
and sorry for late reply! I was kinda busy.
Actually i really love Semantic-UI and I want to keep it and try to fix problems! :)
I think its better to refer to your repo in readme, so we have both versions.
What do you think?

**Comment by Grawl** [comment]
I think we must keep only one demo without visual regressions
